### ISSUE TITLE
React Router - Upgrade to v5?

### ISSUE THREAD

**Issue by apfister** [Esri/esri-react-boot#1]
Just had an issue trying to get routes to render properly using `<Link>` components. The route would render on a full page refresh, but not when using the `<Link to="/myroute" />` component in a Header. After some research that really didn't get me anywhere, I just tried upgrading to `"react-router-dom": "5.0.0"` and the Link components started working. Wish I could be more helpful about what the actual problem was, but hopefully this can be of use to anyone else experiencing the same thing.

**Comment by r-watkins** [comment]
Thanks for raising the issue @apfister and for the potential fix. I'll do some research myself and see if I can get it resolved.

**Comment by r-watkins** [comment]
This project has been refactored and updated, the issue should be fixed now but let me know if you are still experiencing the problem.
