### ISSUE TITLE
Consistency issues found while following Esri Events video https://www.youtube.com/watch?v=GTXL8YfGS9M

### ISSUE THREAD

**Issue by FergusDevelopmentLLC** [Esri/esri-react-boot#2]
Following basic examples from:
https://www.youtube.com/watch?v=GTXL8YfGS9M

**esri-react-boot/src/components/esri/map/Map.js**
Line 48 change to:
this.props.config.mapConfig,

(the Map.js example did not work without this change)

Line 84 change to:
this.props.mapLoaded();

**esri-react-boot/src/components/esri/map/SceneViewExample.js**
Line 48 change to:
this.props.config.mapConfig,

Line 84 change to:
this.props.mapLoaded();

**Details here:** https://docs.google.com/document/d/17tYzUF45GF-EiWqy5DZ2mDTvjnBUiRGIRbko8-iPrLY/edit?usp=sharing

**Comment by r-watkins** [comment]
Sorry it took me so long to respond to this. I'll watch the video and see if it makes sense to sync things up. I'll be moving this project towards more modern best practices like hooks and the ArcGIS Webpack plugin (hopefully...) so this issue may not stay relevant in the end. I'll leave it open though until the changes are officially made though so people have a point of reference. Thanks for the comment.

**Comment by r-watkins** [comment]
This video will unfortunately no longer be applicable with the current updates being made.
